def readMatrix(f_in):
    '''
    Read .mat file generated by octave/matlab as a numpy array.
    '''
    import yaml
    import numpy as np

    # If file, load directly
    if f_in.find('yaml') == -1:
        f_in_data = f_in
        
    # If yaml, load data_file.
    else:
        config = yaml.load(open(f_in))
        f_in_data = 'data/' + config['data_file']

    data = np.loadtxt(f_in_data)
        
    return data
